### ISSUE TITLE
일부 코드에 대한 원 출처를 표시하시기 바랍니다.

### ISSUE THREAD

**Issue by dlcjsdltlq** [keemwonjung123/cleanse#1]
안녕하세요. https://github.com/dlcjsdltlq/dcinside-cleaner 의 개발자입니다.
본 프로젝트의 src/cleaner.py 스크립트가 원 프로젝트의 dcinside_cleaner/dcinside_cleaner.py 스크립트를 일부 수정했음을 확인했습니다. 
속히 MIT 허가서의 사용 조건에 따라 저작권과 라이선스에 대한 고지를 하시기 바랍니다.
감사합니다.

**Comment by keemwonjung123** [comment]
안녕하세요.

제가 저작권과 라이선스에 대해 무지했습니다.
깊은 사과의 말씀 드립니다.
README.md 파일과 소스코드에 @dlcjsdltlq 님의 코드를 사용하였음을 고지하였으니 확인해주시면 감사하겠습니다.

다시 한번 죄송합니다.

**Comment by dlcjsdltlq** [comment]
감사합니다
