### ISSUE TITLE
악!! 클리너에 아이디와 비번을 저장하는 기능을 추가해주실수 있는 여부에 대한 궁금증을

### ISSUE THREAD

**Issue by woofingcough** [keemwonjung123/cleanse#2]
여쭤도 될지에 대해서 물어보는 것이 가능한지 의문을 품어도 되는지에 대한 궁금증을 해소하고자 하는 것이 올바른 일인지 문의를 드려도 되는지 질문하고싶은 욕구를 표출해도 실례가 아닌지에 대해 답변을 요청하는 것이 무리는 아닌지 물어도 되겠습니까?

**Comment by lxxseunghh** [comment]
안녕하세요.

추후 업데이트가 있다면 반드시 해당 기능을 추가하도록 하겠습니다.
다만 큰 오류가 발견되지 않는 한 당분간은 업데이트를 진행하지 않을 것 같습니다.

감사합니다.

**Comment by keemwonjung123** [comment]
안녕하세요.

추후 업데이트가 있다면 반드시 해당 기능을 추가하도록 하겠습니다.
다만 큰 오류가 발견되지 않는 한 당분간은 업데이트를 진행하지 않을 것 같습니다.

감사합니다.

**Comment by woofingcough** [comment]
악!! 감사를 표출해도 되는지에 대해 의문을 가지는 것이 올바른 일인지에 대한 궁금증을 가지는 것이 무리가 아닌지에 대한 궁금증을 가지는것에대해 여쭈어도 되겠습니까?!!
